#!/bin/bash

cp EcoSim run1/
cp EcoSim run2/
cp EcoSim run3/
cp EcoSim run4/
cp EcoSim run5/
cp EcoSim run6/
cp EcoSim run7/
cp EcoSim run8/
cp EcoSim run9/
cp EcoSim run10/
cp EcoSim run11/
cp EcoSim run12/
cp EcoSim run13/
cp EcoSim run14/
cp EcoSim run15/
cp EcoSim run16/
cp EcoSim run17/
cp EcoSim run18/
cp EcoSim run19/
cp EcoSim run20/

cp Parameters1.txt run1/
cp Parameters1.txt run2/
cp Parameters1.txt run3/
cp Parameters1.txt run4/
cp Parameters1.txt run5/
cp Parameters1.txt run6/
cp Parameters1.txt run7/
cp Parameters1.txt run8/
cp Parameters1-Full.txt run9/Parameters1.txt
cp Parameters1-Full.txt run10/Parameters1.txt
cp Parameters1.txt run11/
cp Parameters1.txt run12/
cp Parameters1.txt run13/
cp Parameters1.txt run14/
cp Parameters1.txt run15/
cp Parameters1.txt run16/
cp Parameters1.txt run17/
cp Parameters1.txt run18/
cp Parameters1-Full.txt run19/Parameters1.txt
cp Parameters1-Full.txt run20/Parameters1.txt

cp RunEcoSim.sh run1/
cp RunEcoSim.sh run2/
cp RunEcoSim.sh run3/
cp RunEcoSim.sh run4/
cp RunEcoSim.sh run5/
cp RunEcoSim.sh run6/
cp RunEcoSim.sh run7/
cp RunEcoSim.sh run8/
cp RunEcoSim.sh run9/
cp RunEcoSim.sh run10/
cp RunEcoSim.sh run11/
cp RunEcoSim.sh run12/
cp RunEcoSim.sh run13/
cp RunEcoSim.sh run14/
cp RunEcoSim.sh run15/
cp RunEcoSim.sh run16/
cp RunEcoSim.sh run17/
cp RunEcoSim.sh run18/
cp RunEcoSim.sh run19/
cp RunEcoSim.sh run20/